Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -19,6 +19,25 @@ on:
         description: 'Context for Docker build'
         required: true
         type: string
+      ACR_LOGIN_SERVER:
+        description: 'Azure Container Registry login server'
+        required: true
+        type: string
+      ResourceGroup:
+        description: 'Azure Resource Group'
+        required: true
+        type: string
+    secrets:
+      ACR_USERNAME:
+        description: 'ACR_Username'
+        required: true
+      ACR_PASSWORD:
+        description: 'ACR_Password'
+        required: true
+      AZURE_CREDENTIALS:
+        description: 'AZURE_CREDENTIALS'
+        required: true   
+    
 
 jobs:
   build:
@@ -34,14 +53,35 @@ jobs:
         run: |
           docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.image-name }}:${{ inputs.tag }} ${{ inputs.context }}
           docker save ${{ inputs.image-name }}:${{ inputs.tag }} -o ${{ inputs.image-name }}_${{ inputs.tag }}.tar
-        
-      - name: Upload Docker image as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ inputs.image-name }}-image
-          path: ${{ inputs.image-name }}_${{ inputs.tag }}.tar
           
       - name: List Docker images
         run: |
           echo "Listing Docker images..."
           docker images
+          
+      - name: Log in to Azure CLI
+        uses: azure/login@v2
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+       
+      - name: Azure CLI script
+        uses: azure/cli@v2
+        with:
+          azcliversion: latest
+          inlineScript: |
+            az account show
+      
+      - name: Log in to Azure Container Registry (ACR)
+        uses: azure/docker-login@v2
+        with:
+          login-server: ${{ inputs.ACR_LOGIN_SERVER }}
+          username: ${{ secrets.ACR_USERNAME }}
+          password: ${{ secrets.ACR_PASSWORD }}
+                  
+      - name: Push Docker image to ACR
+        run: |
+          docker tag ${{ inputs.image-name }}:${{ inputs.tag }} ${{ inputs.ACR_LOGIN_SERVER }}/${{ inputs.image-name }}:${{ github.sha }}
+          echo "Listing Docker images..."
+          az acr repository show-tags --name ${{ inputs.ACR_LOGIN_SERVER }} --repository ${{ inputs.image-name }} --output table | grep ${{ github.sha }} && echo "Image successfully pushed!" || echo "Image not found in ACR!"
+          docker push ${{ inputs.ACR_LOGIN_SERVER }}/${{ inputs.image-name }}:${{ github.sha }}
+    
